import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    //   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    // Custom sidebar navigation
    docs: [
        {
            type: 'doc',
            id: 'index',
            label: 'Overview',
        },
        {
            type: 'doc',
            id: 'get-started',
            label: 'Getting Started',
        },
        {
            type: 'category',
            label: 'Command Line Usage',
            link: { type: 'doc', id: 'command-line/index' },
            items: [
                {
                    type: 'doc',
                    id: 'command-line/index',
                    label: 'Overview',
                },
                {
                    type: 'doc',
                    id: 'command-line/build',
                    label: 'Build',
                },
                {
                    type: 'doc',
                    id: 'command-line/convert-gulp',
                    label: 'Convert Gulp',
                },
                {
                    type: 'doc',
                    id: 'command-line/copy-files',
                    label: 'Copy Files',
                },
                {
                    type: 'doc',
                    id: 'command-line/css',
                    label: 'CSS',
                },
                {
                    type: 'doc',
                    id: 'command-line/environment',
                    label: 'Environment',
                },
                {
                    type: 'doc',
                    id: 'command-line/export',
                    label: 'Export',
                },
                {
                    type: 'doc',
                    id: 'command-line/fonts',
                    label: 'Fonts',
                },
                {
                    type: 'doc',
                    id: 'command-line/ftp',
                    label: 'FTP',
                },
                {
                    type: 'doc',
                    id: 'command-line/icons',
                    label: 'Icons',
                },
                {
                    type: 'doc',
                    id: 'command-line/images',
                    label: 'Images',
                },
                {
                    type: 'doc',
                    id: 'command-line/initialize',
                    label: 'Initialize',
                },
                {
                    type: 'doc',
                    id: 'command-line/javascript',
                    label: 'Javascript',
                },
                {
                    type: 'doc',
                    id: 'command-line/package-json',
                    label: 'Package.json',
                },
                {
                    type: 'doc',
                    id: 'command-line/pull',
                    label: 'Pull',
                },
                {
                    type: 'doc',
                    id: 'command-line/start',
                    label: 'Start',
                },
                {
                    type: 'doc',
                    id: 'command-line/templates',
                    label: 'Templates',
                },
                {
                    type: 'doc',
                    id: 'command-line/theme',
                    label: 'Theme',
                },
                {
                    type: 'doc',
                    id: 'command-line/watch',
                    label: 'Watch',
                },
            ],
        },
        {
            type: 'category',
            label: 'Configuration',
            link: { type: 'doc', id: 'configuration/index' },
            items: [
                {
                    type: 'doc',
                    id: 'configuration/index',
                    label: 'Overview',
                },
                {
                    type: 'category',
                    label: 'Configuration Examples',
                    link: { type: 'generated-index' },
                    items: [
                        {
                            type: 'doc',
                            id: 'configuration/examples/cjs',
                            label: 'CommonJS',
                        },
                        {
                            type: 'doc',
                            id: 'configuration/examples/js',
                            label: 'JavaScript',
                        },
                        {
                            type: 'doc',
                            id: 'configuration/examples/json',
                            label: 'JSON',
                        },
                        {
                            type: 'doc',
                            id: 'configuration/examples/yaml',
                            label: 'Yaml',
                        },
                    ],
                },
                {
                    type: 'doc',
                    id: 'configuration/css',
                    label: 'CSS',
                },
                {
                    type: 'doc',
                    id: 'configuration/icons',
                    label: 'Icons',
                },
                {
                    type: 'doc',
                    id: 'configuration/images',
                    label: 'Images',
                },
                {
                    type: 'doc',
                    id: 'configuration/javascript',
                    label: 'Javascript',
                },
                {
                    type: 'doc',
                    id: 'configuration/package-json-scripts',
                    label: 'Package.json Scripts',
                },
            ],
        },

        {
            type: 'category',
            label: 'Development',
            link: { type: 'doc', id: 'development/index' },
            items: [
                {
                    type: 'doc',
                    id: 'development/index',
                    label: 'Overview',
                },
                {
                    type: 'doc',
                    id: 'development/local',
                    label: 'Local development',
                },
            ],
        },
        'changelog',
    ],

    // But you can create a sidebar manually
    /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
